import {StyleSheet} from 'react-native';
import {Colors} from '../../constants/color.constants';
import {FontSize} from '../../constants/fontsize.constants';

export const styles = StyleSheet.create({
  bannerImage: {
    width: '100%',
    height: 300,
    flexDirection: 'row',
  },
  cubeOne: {
    left: '13%',
    top: '55%',
    zIndex: 10,
    height: 100,
    width: 90,
    position: 'absolute',
    resizeMode: 'stretch',
  },
  cubeTwo: {
    left: '70%',
    top: '85%',
    zIndex: 16,
    height: 75,
    width: 70,
    position: 'absolute',
    resizeMode: 'stretch',
  },
  blockOne: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderTopWidth: 0,
    borderRightWidth: 70,
    borderBottomWidth: 55,
    borderLeftWidth: 0,
    borderTopColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: Colors.DarkGreen,
    borderLeftColor: 'transparent',
  },
  blockTwo: {
    width: 70,
    height: 165,
    backgroundColor: Colors.DarkGreen,
  },
  blockThree: {
    marginTop: 195,
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderTopWidth: 0,
    borderRightWidth: 90,
    borderBottomWidth: 105,
    borderLeftWidth: 0,
    borderTopColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: Colors.DarkGreen,
    borderLeftColor: 'transparent',
  },
  blockFour: {
    marginTop: 235,
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 65,
    borderLeftWidth: 130,
    borderTopColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: Colors.DarkGreen,
    borderLeftColor: 'transparent',
  },
  blockFive: {
    marginTop: 235,
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderTopWidth: 0,
    borderRightWidth: 150,
    borderBottomWidth: 65,
    borderLeftWidth: 0,
    borderTopColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: Colors.DarkGreen,
    borderLeftColor: 'transparent',
  },
  container: {
    flex: 1,
    backgroundColor: Colors.DarkGreen,
  },
  sloganContainer: {
    marginTop: 30,
    width: '64%',
    marginLeft: '18%',
  },
  sloganTitle: {
    color: Colors.White,
    fontSize: FontSize.ExtraLarge,
    marginBottom: 10,
  },
  lineWithLogo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  oneLine: {
    marginTop: 24,
    width: '30%',
    height: 1,
    backgroundColor: Colors.White,
  },
  logo: {
    width: 30,
    height: 50,
    resizeMode: 'stretch',
  },
  seasonFruitContainer: {
    marginTop: 50,
    paddingHorizontal: 15,
  },
  seasonFruitTitle: {
    color: Colors.White,
    fontSize: FontSize.MediumLarge,
    textAlign: 'center',
    marginBottom: 20,
  },
  fruitCard: {
    marginRight: 20,
    width: 70,
    height: 50,
    borderRadius: 10,
    backgroundColor: Colors.DarkOrange,
    justifyContent: 'center',
  },
  fruitLogo: {
    width: 30,
    height: 30,
    resizeMode: 'stretch',
    marginLeft: 20,
  },
});
