import {StyleSheet} from 'react-native';
import {Colors} from '../../constants/color.constants';
import {FontSize} from '../../constants/fontsize.constants';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.DarkGreen,
  },
  goBackContainer: {
    paddingLeft: '3%',
    marginTop: 10,
  },
  storeImageContainer: {
    width: 260,
    height: 260,
    borderRadius: 260,
    backgroundColor: 'white',
    overflow: 'hidden',
    position: 'absolute',
    top: 60,
    left: -60,
    zIndex: 50,
  },
  storeImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'stretch',
  },
  backgroundLine: {
    width: '120%',
    height: 200,
    resizeMode: 'stretch',
    zIndex: 0,
  },
  storeName: {
    color: Colors.White,
    fontSize: FontSize.Large,
    alignSelf: 'flex-end',
    marginTop: 30,
    width: '43%',
    paddingRight: '2%',
    textAlign: 'center',
  },
  storeDescription: {
    color: Colors.White,
    fontSize: FontSize.Small,
    alignSelf: 'flex-end',
    marginTop: 40,
    width: '100%',
    paddingHorizontal: '2%',
    textAlign: 'center',
  },
  storeInfoContainer: {
    marginTop: 30,
    width: '100%',
    borderBottomWidth: 1,
    borderColor: 'white',
    paddingBottom: 20,
  },
  contactInfoTitle: {
    width: '60%',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    textAlign: 'center',
    color: Colors.White,
    fontSize: FontSize.MediumLarge,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: Colors.White,
    paddingVertical: 3,
    marginBottom: 20,
  },
  contactInfo: {
    width: '90%',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    textAlign: 'center',
    color: Colors.White,
    fontSize: FontSize.Small,
    marginTop: 8,
  },
  productAreaContainer: {
    width: '100%',
    paddingHorizontal: '5%',
  },
  productsTitle: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    textAlign: 'left',
    color: Colors.White,
    fontSize: FontSize.Small,
    marginTop: 8,
  },
  productContainer: {
    width: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-evenly',
  },
  productBackground: {
    flexBasis: '98%',
    backgroundColor: Colors.FilterGreen,
    height: 100,
    marginVertical: 5,
    borderRadius: 10,
    flexDirection: 'row',
    overflow: 'hidden',
  },
  productImageBackground: {
    width: '35%',
    height: '90%',
    marginTop: '2%',
    borderRadius: 10,
    overflow: 'hidden',
    marginLeft: '2%',
  },
  productImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'stretch',
  },
  productInfoContainer: {
    width: '63%',
    paddingHorizontal: '5%',
    paddingVertical: '1%',
  },
  productName: {
    color: Colors.White,
    fontWeight: '600',
    fontSize: FontSize.Small,
  },
  productAmount: {
    color: Colors.White,
    fontSize: FontSize.Small,
  },
  productPublishDate: {
    color: Colors.White,
    fontSize: FontSize.Small,
  },
  productDescription: {
    color: Colors.White,
    fontSize: FontSize.Small,
  },
});
